version: '3'
networks:
  outside:
    external: true
services:
  client_web_nginx:
    image: nginx:stable-perl
    container_name: client_web_nginx
    restart: unless-stopped
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ../dist:/home/dist
    ports:
      - '3001:3001'
    networks:
      - outside
