version: '3'
networks:
  outside:
    external: true
services:
  nginx:
    image: nginx:stable-perl
    container_name: nginx_static
    volumes:
      - ./nginx-local:/etc/nginx/conf.d
      - ../dist:/home/dist
    ports:
      - '3001:3001'
    networks:
      - outside


