version: '3'
networks:
  outside:
    external: true
services:
  node:
    image: bitnami/node:18.14.2
    container_name: node
    restart: unless-stopped
    volumes:
      - ../:/app
    ports:
      - '3000:3000'
    env_file:
      - ./.env
    command: >
      bash -c '
        yarn && node dist/server.js
      '
    networks:
      - outside


