version: '3'

services:
  db:
    image: postgres
    container_name: postgres_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
volumes:
  pgdata:
    driver: local
