version: '3'

networks:
  outside:
    external: true
services:
  db:
    image: postgres
    container_name: postgres_db
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    networks:
      - outside
volumes:
  pgdata:
    driver: local
