version: '3'
networks:
  outside:
    external: true
services:
  lego:
    image: goacme/lego:v4.10.0
    container_name: lego
    volumes:
      - lego:/.lego
    ports:
      - '80:80'
      - '443:443'
    env_file:
      - ./.env
    command:
      '--accept-tos --dns route53 --domains="${API_DOMAIN}" --domains="${STATIC_DOMAIN}" --domains="${SIP_DOMAIN}" --email="${EMAIL}" run'
  reverse_nginx:
    image: nginx:stable-perl
    container_name: reverse_nginx
    restart: unless-stopped
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - lego:/etc/nginx/certs
      - logs:/var/log/nginx/logs
    ports:
      - '443:8443'
      - '80:8080'
    networks:
      - outside
    depends_on:
      lego:
        condition: service_completed_successfully
volumes:
  lego:
    driver: local
  logs:
    driver: local
