version: '3'
networks:
  outside:
    external: true
services:
  nginx_reverse:
    image: nginx:stable-perl
    container_name: nginx_reverse
    volumes:
      - ./nginx-local:/etc/nginx/conf.d
      - ../certs/tls.crt:/etc/nginx/${API_DOMAIN_LOCAL}.crt
      - ../certs/tls.key:/etc/nginx/${API_DOMAIN_LOCAL}.key
      - ../certs/tls.crt:/etc/nginx/${STATIC_DOMAIN_LOCAL}.crt
      - ../certs/tls.key:/etc/nginx/${STATIC_DOMAIN_LOCAL}.key
      - logs:/var/log/nginx/logs
    ports:
      - '443:8443'
      - '80:8080'
    networks:
      - outside
volumes:
  logs:
    driver: local


