version: '3'
networks:
  outside:
    external: true
services:
#  lego:
#    image: goacme/lego:v4.10.0
#    container_name: lego
#    volumes:
#      - certs:/.lego/certificates
#    ports:
#      - '80:80'
#      - '443:443'
#    env_file:
#      - ./.env
#    command:
#      '--accept-tos --dns route53 --domains="${API_DOMAIN}" --domains="${STATIC_DOMAIN}" --domains="${SIP_DOMAIN}" --email="${EMAIL}" run'
#    healthcheck:
#      test: ['CMD-SHELL', '[ -f /.lego/certificates/${API_DOMAIN}.crt ]']
#      interval: 10s
#      timeout: 10s
#      retries: 120
  reverse_nginx:
    image: nginx:stable-perl
    container_name: reverse_nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - certs:/etc/nginx/certs
      - logs:/var/log/nginx/logs
    ports:
      - '443:8443'
      - '80:8080'
    networks:
      - outside
#    depends_on:
#      lego:
#        condition: service_healthy
volumes:
  certs:
    driver: local
  logs:
    driver: local
